// Package emoji provides the emoji and kaomoji datasets shown by the icon
// picker (Ctrl+]).
package emoji

// Icon is a single pickable glyph with a searchable name.
type Icon struct {
	Glyph string
	Name  string
}

// Set is one browsable icon collection (a tab in the picker).
type Set struct {
	Label       string
	Icons       []Icon
	CommonNames map[string]bool // Icon.Name -> true, for the "Common X" section
}

// Emoji is the full Unicode emoji set (see emoji_data.go, generated by
// cmd/gen-icondata), filtered to glyphs safeWidth confirms render without
// corrupting a textinput/textarea's cursor math, and further filtered by
// requireKnownWide to exclude emoji too new for the pinned go-runewidth
// version's width table.
var Emoji = Set{Label: "Emoji", Icons: requireKnownWide(filterSafe(emojiIcons)), CommonNames: emojiCommonNames}

// Kaomoji is a curated kaomoji corpus (see kaomoji_data.go), filtered the
// same way as Emoji.
var Kaomoji = Set{Label: "Kaomoji", Icons: filterSafe(kaomojiIcons), CommonNames: kaomojiCommonNames}
