{
  "data": {
    "mutedTopics": [],
    "followedTopics": [
      "cyberspace",
      "introduction",
      "linux",
      "ai",
      "politics",
      "gaming",
      "tech",
      "thoughts"
    ],
    "custom_theme": {
      "fg": "#000",
      "bg": "#eaeae4",
      "fgDim": "#3a3a3a",
      "border": "#9aa49d",
      "code": "#58625e",
      "codeBg": "#b4c2aa",
      "disableTextGlow": false,
      "disableTextAntialiasing": false,
      "enableNoise": false,
      "enableCRTBox": false,
      "enableLigatures": false,
      "softness": "off"
    },
    "showFollowerCount": false,
    "hideImagesInFeed": false,
    "hideAudioInFeed": false,
    "showProfilePictures": false,
    "showChatIcons": false,
    "reduceMotion": false,
    "autoWatchOnReply": true,
    "notifications": {
      "unfollowed": true,
      "dm_message": true,
      "bookmark": true,
      "new_follower": true,
      "poke": true,
      "reply": true,
      "thread_reply": true,
      "new_post_following": true,
      "new_post_friend": true,
      "guild_new_thread": true,
      "chat_mention": true
    },
    "imagePixelSize": "sharp",
    "iconTheme": "pixel",
    "timeDisplayFormat": "relative",
    "useLegacyMenuOrder": false,
    "keyboardBindings": {
      "reply": "r",
      "save": "s",
      "expand": "e",
      "notePublish": "p",
      "noteDelete": "d",
      "follow": "f",
      "watch": "w",
      "up": "ArrowUp",
      "down": "ArrowDown",
      "left": "ArrowLeft",
      "right": "ArrowRight",
      "commandPaletteKey": "k",
      "commandPaletteModifier": "auto",
      "paletteItems": [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "0"
      ],
      "playerToggle": "p",
      "playerToggleModifier": "alt",
      "playerNext": "ArrowRight",
      "playerNextModifier": "alt",
      "playerPrev": "ArrowLeft",
      "playerPrevModifier": "alt",
      "paletteDirectory": "",
      "paletteSearch": "",
      "paletteGuilds": "",
      "paletteWiki": "",
      "paletteSettings": ""
    },
    "keyboardPreset": "default",
    "defaultPublicPost": false,
    "filterNSFW": false,
    "dismissedWelcomeCard": true
  }
}
