// Command gen-icondata converts Unicode's emoji-test.txt into
// internal/emoji/emoji_data.go. It's a one-time dev tool, not part of the
// build — re-run it by hand when Unicode ships a new emoji-test.txt:
//
//	curl -o /tmp/emoji-test.txt https://unicode.org/Public/emoji/latest/emoji-test.txt
//	go run ./cmd/gen-icondata /tmp/emoji-test.txt > internal/emoji/emoji_data.go
package main

import (
	"bufio"
	"fmt"
	"os"
	"strconv"
	"strings"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: gen-icondata <path-to-emoji-test.txt>")
		os.Exit(1)
	}
	f, err := os.Open(os.Args[1])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer f.Close()

	type icon struct{ glyph, name string }
	var icons []icon

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		if !strings.Contains(line, "; fully-qualified") {
			continue
		}
		hashIdx := strings.IndexByte(line, '#')
		if hashIdx < 0 {
			continue
		}
		// "😀 E1.0 grinning face" -> glyph, version, name
		fields := strings.SplitN(strings.TrimSpace(line[hashIdx+1:]), " ", 3)
		if len(fields) != 3 {
			continue
		}
		icons = append(icons, icon{glyph: fields[0], name: fields[2]})
	}
	if err := scanner.Err(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	var b strings.Builder
	b.WriteString("// Code generated by cmd/gen-icondata from Unicode's emoji-test.txt. DO NOT EDIT.\n")
	b.WriteString("// Source: https://unicode.org/Public/emoji/latest/emoji-test.txt\n\n")
	b.WriteString("package emoji\n\n")
	fmt.Fprintf(&b, "var emojiIcons = []Icon{\n")
	for _, ic := range icons {
		fmt.Fprintf(&b, "\t{Glyph: %s, Name: %s},\n", strconv.Quote(ic.glyph), strconv.Quote(ic.name))
	}
	b.WriteString("}\n\n")

	// A curated subset shown as "Common Emoji" — CLDR has no such flag, so
	// this is a hand-picked list of names matched against emojiIcons above.
	common := []string{
		"grinning face", "grinning face with big eyes", "face with tears of joy",
		"smiling face with heart-eyes", "smiling face with sunglasses", "thinking face",
		"melting face", "winking face", "loudly crying face", "pleading face",
		"folded hands", "waving hand", "clapping hands", "flexed biceps",
		"thumbs up", "thumbs down", "eyes", "brain", "skull",
		"red heart", "orange heart", "fire", "star", "sparkles",
		"hundred points", "check mark button", "cross mark", "warning",
		"party popper", "rocket", "seedling", "gem stone",
	}
	fmt.Fprintf(&b, "var emojiCommonNames = map[string]bool{\n")
	for _, name := range common {
		fmt.Fprintf(&b, "\t%s: true,\n", strconv.Quote(name))
	}
	b.WriteString("}\n")

	os.Stdout.WriteString(b.String())
}
